package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"strings"
	"time"

	"github.com/quacklemtduck/gotots/visitor"
)

var disclaimer = `// Code generated by Gotots. DO NOT EDIT.
//
// This file was automatically generated by Gotots on %s.
// Any changes to this file will be overwritten when the code is regenerated.
//
// If you need to modify the behavior, consider updating the source/template or configuration used for generation.

`

const DEV = false

func main() {

	if os.Getenv("GOFILE") == "" {
		log.Fatalln("No GOFILE supplied, are you sure you are doing this correctly?")
	}
	log.Printf("Generating for file %s\n", os.Getenv("GOFILE"))
	cwd, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	file := fmt.Sprintf("%s/%s", cwd, os.Getenv("GOFILE"))
	log.Printf("Full path: %s\n", file)
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, file, nil, 0)
	if err != nil {
		panic(err)
	}
	if !DEV {
		// Create a file to replace stdout
		outFile, err := os.Create(fmt.Sprintf("%s.ts", strings.TrimSuffix(os.Getenv("GOFILE"), ".go")))
		if err != nil {
			fmt.Println("Error creating file:", err)
			return
		}
		defer outFile.Close()
		os.Stdout = outFile
	}

	fmt.Printf(disclaimer, time.Now().Format("2006-01-02 15:04:05"))
	var v visitor.Visitor = visitor.New(os.Getenv("GOFILE"))
	ast.Walk(v, f)

}
